### ISSUE TITLE
Current state of development

### ISSUE THREAD

**Issue by tarbrain** [venmo/slather#107]
Hello slather developers,

I have noticed that development activity on this project has slowed down over the last four months. Could anyone of you give me an update on how the project is currently maintained? There are open issues related to Xcode 7 and the changes that have been introduced with it, coverage formats in particular.

Since many of us are using slather not only on their pet projects but also on the job we need development in the flow especially when working actively on iOS 9 / watchOS / tvOS projects.

I would love to hear from you.

Regards
tarbrain

**Comment by tarbrain** [comment]
Hello @marklarr @ayanonagon 

Is there a chance to give me maintainer privileges for this repo? I would like to participate a little bit more in the development of slather.

Regards
tarbrain

**Comment by eliperkins** [comment]
I'll put my two cents in here.

The team I'm on has used Slather much less as of late, weening off in favor of other tools. While I'd love to see Slather continued being developed and maintained, I personally have not had the time to maintain it as best as I could.

I'd like to defer the decision to other maintainers of this repo, but I'd be all for adding other maintainers to this repo to keep things moving forward!

**Comment by marklarr** [comment]
Hey @tarbrain. Sorry, I totally agree -- this project has been neglected. I've moved over to working on the payments backend at Braintree, so I'm not doing a lot of iOS development anymore. I'm going to look into getting you setup as a collaborator on this project.

**Comment by tarbrain** [comment]
Thanks for adding me @marklarr.
