### ISSUE TITLE
Code Coverage Data Generation Failed

### ISSUE THREAD

**Issue by perfectpapa** [venmo/slather#117]
i've executed slather setup xx.projct  when i'm  running test with cmd+u it failed:
Code Coverage Data Generation Failed
Unable to retrieve the profile data files from 'iPhone 5s

and the log show
2015-12-14 13:59:28.582 xctest[6447:734168] The bundle “MyTests.xctest” couldn’t be loaded. Try reinstalling the bundle.
2015-12-14 13:59:28.583 xctest[6447:734168 

(dlopen(/Users/wx/Library/Developer/Xcode/DerivedData/My-akiykixzlljhyegfebcgflamfzgb/Build/Intermediates/CodeCoverage/My/Products/Debug-iphonesimulator/MyTests.xctest/MyTests, 265): Symbol not found: _OBJC_CLASS_$_AgreementViewController
  Referenced from: /Users/wx/Library/Developer/Xcode/DerivedData/My-akiykixzlljhyegfebcgflamfzgb/Build/Intermediates/CodeCoverage/My/Products/Debug-iphonesimulator/MyTests.xctest/MyTests
  Expected in: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Xcode/Agents/xctest
 in /Users/wx/Library/Developer/Xcode/DerivedData/My-akiykixzlljhyegfebcgflamfzgb/Build/Intermediates/CodeCoverage/My/Products/Debug-iphonesimulator/MyTests.xctest/MyTests)

Program ended with exit code: 83

**Comment by tarbrain** [comment]
Currently slather is not compatible with Xcode 7, since Xcode 7 is using a different coverage format.

Support for profdata format is currently in the works.

**Comment by perfectpapa** [comment]
@tarbrain thx  is there any other way to get report?

**Comment by tarbrain** [comment]
Only if you use Xcode 6. Slather relies on the old gcov format which is deprecated in Xcode 7.

Here is a writeup which might help you  if you look for another solution until the next slather update:

http://mgrebenets.github.io/mobile%20ci/2015/09/21/code-coverage-for-ios-xcode-7/

**Comment by perfectpapa** [comment]
thx for your reply i'll try it
