### ISSUE TITLE
question, is there ways to only run slather on new or modified code?

### ISSUE THREAD

**Issue by joshrlesch** [venmo/slather#118]
Want to start getting unit tests into our app. My initial thought is to have a github blocker that if new or modified code gets checked and there needs to be a certain % of code coverage for that PR.

Is this possible with slather?

**Comment by tarbrain** [comment]
Sounds like something that should be part of the build process you would perform on a continuous integration system.

If you want to do this on a development computer you could write a script which launches the tests only if certain criteria are fulfilled (your git status shows uncommitted changes or your local branch differs from the remote branch etc.).

I dont think this should be a feature of slather itself.

**Comment by joshrlesch** [comment]
Ok good to know, thanks for the response.

**Comment by tarbrain** [comment]
You're welcome :-)
