### ISSUE TITLE
Wrong gem releases

### ISSUE THREAD

**Issue by tamastimar** [venmo/slather#120]
Hi there,

I've tried to use `cobertura_xml` coverage service but I've got the following error:
`coverage_service=:'' is not a valid coverage service. Try 'terminal' or 'coveralls' (ArgumentError)`

I get this same message even if install 1.8.2 specifically. That message was in 1.4.0 last time. So it seems that wrong code downloaded when it's installed via RubyGems.

Another symptom: gemspec of 1.8.2 says that it depends on `xcodeproj` 0.28.0 but [on RubyGems.org](https://rubygems.org/gems/slather/versions/1.8.2) it is `xcodeproj` 0.17. (which was the dependency in `slather` 1.4.0)

Could you look after it? Thanks.

**Comment by tamastimar** [comment]
1.8.1 has the right dependencies (https://rubygems.org/gems/slather/versions/1.8.1) so it seems the problem is with 1.8.2 release.

**Comment by marklarr** [comment]
Released 1.8.3, which should be functional. Try it out and close the issue please if it works :smile:

**Comment by Ashton-W** [comment]
Looks correct now, thanks.

**Comment by tamastimar** [comment]
Looks good, thanks.
