### ISSUE TITLE
Slather can't find the default test target gcda files.

### ISSUE THREAD

**Issue by mindw0rk** [venmo/slather#47]
Hi guys!

I was trying to use slather for the first time and noticed that it couldn't find the gcda coverage files for my test target, specifying the exact location of the test target with the -b flag fixed it.

Is this working the way it is intended to work or is there something about my project configuration that makes it fail?

I'm using Xcode 6.1.1 and my tests are strictly unit tests built into a separate target (I'm not hooking the tests on the actual application).

Thank you!

**Comment by marklarr** [comment]
`-b` is not supposed to be the location of the test target, but the directory where Xcode puts your `gcda` files -- which by default is DerivedData. You can change this by setting this environment variables `OBJROOT` and `SYMROOT`, (I think you might only need one of those... not sure), but default should be DerivedData.

**Comment by mindw0rk** [comment]
Regarding the `b` target - yes, I mean where xcode puts gcda files for the test target.

Now the thing is that they are inside DerivedData, but not in my application target folder, but the folder for my test target (I include my classes from the actual application to the testing target separately).

I'm assuming that slather is looking for coverage files inside the application target intermediates folder, instead of the test target intermediates folder.

Path for the application target (contains no gcda files):
```<THE_PROJECT>/DerivedData/TheStream/Build/Intermediates/ProjectName.build/Debug-iphonesimulator/ProjectName.build/Objects-normal/x86_64```

Path for the test target (contains all the gcda files I need):
```<THE_PROJECT>/DerivedData/TheStream/Build/Intermediates/ProjectName.build/Debug-iphonesimulator/ProjectNameTests.build/Objects-normal/x86_64```

So specifying the latter path with `-b` works flawlessly whereas not specifying it fails.

**Comment by marklarr** [comment]
[This code](https://github.com/venmo/slather/blob/master/lib/slather/project.rb#L42) should be looking for any `gcno` file underneath `/Library/Developer/Xcode/DerivedData/`, so it seems like it should be able to find them...

You do say `<THE_PROJECT>/DerivedData`, though. Is your DerivedData stored under your project's path? It's usually just under `Library/Developer/Xcode`

**Comment by mindw0rk** [comment]
I've defined it in the project settings, so yeah. Could that be the problem? Slather looks for Derived Data only inside `Library/Developer/Xcode`?

**Comment by marklarr** [comment]
Yup -- that's it. Slather doesn't look at your Xcode application settings for a custom location. It looks like you'll just have to specify the path, but the good news is that it shouldn't be hard to do that in your `.slather` file since it's relative to the project.
