### ISSUE TITLE
Project Setup fails, .pbxproj file breaks

### ISSUE THREAD

**Issue by evils** [venmo/slather#48]
I'm currently looking into slather as our tool of choice to measure code coverage in connection with coveralls.io

When I initially tried to setup slather as mentioned in the README.txt through 
    slather setup Project.xcodeproj 
my whole .pbxproj file got rewritten (as what the diff showed me) due to different ways of formatting the file.

My next step, was using 
    slather coverage -s Project.xcodeproj
to measure my code coverage. Unfortunately, this is where everything breaks and slather starts to throw the stack trace at me. 

The error message looks like this:
```
Slathering...
/Users/florian/.rvm/gems/ruby-2.2.0/gems/slather-1.5.4/lib/slather/project.rb:49:in `coverage_files': No coverage files found. Are you sure your project is setup for generating coverage files? Try `slather setup your/project.pbxproj` (StandardError)
	from /Users/florian/.rvm/gems/ruby-2.2.0/gems/slather-1.5.4/lib/slather/coverage_service/simple_output.rb:13:in `post'
	from /Users/florian/.rvm/gems/ruby-2.2.0/gems/slather-1.5.4/bin/slather:64:in `post'
	from /Users/florian/.rvm/gems/ruby-2.2.0/gems/slather-1.5.4/bin/slather:36:in `execute'
	from /Users/florian/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
	from /Users/florian/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.3/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Users/florian/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
	from /Users/florian/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
	from /Users/florian/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.3/lib/clamp.rb:6:in `Clamp'
	from /Users/florian/.rvm/gems/ruby-2.2.0/gems/slather-1.5.4/bin/slather:6:in `<top (required)>'
	from /Users/florian/.rvm/gems/ruby-2.2.0/bin/slather:23:in `load'
	from /Users/florian/.rvm/gems/ruby-2.2.0/bin/slather:23:in `<main>'
	from /Users/florian/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/florian/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

After investigating into this for several hours, I found another "example" project which is using Slather + Coveralls.io and their slather support is broken as well.
The project I was looking into is the XNGAPIClient, which had their last successful measurement in mid December (see this build [Travis CI](https://travis-ci.org/xing/XNGAPIClient/jobs/44578134#L27) [Coveralls.io](https://coveralls.io/builds/1636659)).

As it's definitely not the difference between XCode 6.1 and XCode 6.1.1 (tried that), I tried to add these flags manually and slather started to work.

So afaik, the setup function of slather is not working right now and should be fixed ASAP as slather is more or less not useable in comparison with Travis CI (only with a customised setup).

**Comment by marklarr** [comment]
So, Slather didn't break the `pbxproj` file -- as you said, it just rewrote it as XML. This is a product of the way that the `xcodeproj` gem works, which also powers gems like Synx and Cocoapods. Issues have been opened up (and closed) on Synx regarding this in the past, https://github.com/venmo/synx/issues/42#issuecomment-53685409, but these issues belong on the `xcodeproj` repo.

As for the stack trace, this is a specific exception case that Synx looks for. If you look at the exception that was raised, it says

<  No coverage files found. Are you sure your project is setup for generating coverage files? Try `slather setup your/project.pbxproj`

This means that Slather couldn't find any `.gcno` underneath the tree `/Library/Developer/Xcode/DerivedData`, the default location for coverage files generated by Xcode. Your issue sounds similar to https://github.com/venmo/slather/issues/47 and I wouldn't be surprised if your coverage files have just been specially configured to go elsewhere, in which case you'll need to specify that location to Slather.

If you can provide an rspec test that exposes this specific bug, then I'd be happy to reopen the issue.

**Comment by marklarr** [comment]
Also: https://github.com/venmo/synx/issues/59
