### ISSUE TITLE
README could include steps to get results into Coverstory?

### ISSUE THREAD

**Issue by orta** [venmo/slather#49]
Are you trying to see these visually locally? Would be interesting to be able to open straight in Coverstory

https://code.google.com/p/coverstory/

Related: https://github.com/socialize/socialize-project-helpers-ios/blob/master/export-coverstory.sh

**Comment by ayanonagon** [comment]
I’ve never used `coverstory` before, but if you think this is something that people would like to use, pull-requests are welcome! :octocat:

**Comment by tarbrain** [comment]
I find it would be better to have a generic html output service in slather which generates html pages that can be viewed in the browser of your choice. With a nice stylesheet and ruby templates.

What do you think?

**Comment by marklarr** [comment]
@tarbrain that'd be cool, but more work probably :smile:

**Comment by marklarr** [comment]
Now that we have #82, I think we can close this out :)
