### ISSUE TITLE
slather is not picking up coverage files

### ISSUE THREAD

**Issue by ben-ng** [venmo/slather#61]
Slather is not picking up the `.gcno` files in my [project's](https://github.com/ben-ng/paq) build directory. To prove this, I ran `tree` on the folder where my project was built and grepped for the files on travis. They're there.

![screen shot 2015-03-27 at 11 40 26 pm](https://cloud.githubusercontent.com/assets/543312/6879710/afd9d16e-d4da-11e4-9a0e-a15e00e48383.png)

My slather config:
```
coverage_service: coveralls
xcodeproj: paq.xcodeproj
ignore:
  - catch.hpp
```

Looking at slather's source, it looks like it either thinks the file has no source file, or that it is in my ignore list. Neither seems to be true.

Is there any way to disable the "no source file" check? I can explicitly give slather the correct build directory to look in using the `-b` flag, so it can just blindly take all the `.gcno` files in there.

**Comment by marklarr** [comment]
v1.7.0 is out and fixes this
