### ISSUE TITLE
Slather unable to find coverage files?

### ISSUE THREAD

**Issue by lazerwalker** [venmo/slather#67]
I've tried to set up two different projects with Slather today (https://github.com/lazerwalker/MTLParseAdapter and https://github.com/intentkit/IntentKit – the former is much smaller/simpler, if you're looking for a test case). Both are failing for the same reason: 

```sh
/Library/Ruby/Gems/2.0.0/gems/slather-1.7.0/lib/slather/project.rb:49:in `coverage_files': No coverage files found. 
Are you sure your project is setup for generating coverage files? 
Try `slather setup your/project.pbxproj` 
(StandardError)
```

Both of these are failing both locally and on Travis (e.g. https://travis-ci.org/lazerwalker/MTLParseAdapter/builds/59264653). 

Poking around existing issues, it seems that's common if you've manually changed where the `gcda` files get placed. However, I haven't changed that for either of these projects. It also doesn't appear to be a local system-wide Xcode config issue, as I have other projects with similar setups that will let themselves be Slathered just fine.

Any thoughts?

**Comment by dasmer** [comment]
@lazerwalker 
Your `source_directory` must be a directory of files that is included in your xcodeproj directly.

As of now, they are internal Pods that are bundled in your workspace.
(https://github.com/lazerwalker/MTLParseAdapter/blob/master/.slather.yml#L4)

You may need to reorganize your project so that your source files have their own framework and tests, that is separate from your example project.

**Comment by lazerwalker** [comment]
Ah, gotcha. Thanks!

Might be worth massaging that error message a bit – I'd assume it wouldn't be hard to manually check the case where no coverage reports are generated, but the specified Xcode project has been set up to generate coverage.

**Comment by dasmer** [comment]
Actually, I think I initially misguided you. You can use local Pods, but you need to add `plugin 'slather'` to your Podfile.

**Comment by lazerwalker** [comment]
Hah, I was literally in the middle of trying that for IntentKit when I saw your comment. Yeah, just adding it to the Podfile works like a charm.

**Comment by dasmer** [comment]
Sorry about that! Glad you got it working :star2:

**Comment by lazerwalker** [comment]
For anyone from The Future following along: using Cocoapods 0.36.4, one of my projects needed me to explicitly tell Travis to `gem install activesupport` to stop it from blowing up when it tried to interpret the Podfile plugin line (see https://github.com/CocoaPods/CocoaPods/issues/3076)
