### ISSUE TITLE
Allow passing Coveralls repo token on CLI or as ENV var

### ISSUE THREAD

**Issue by bgerstle** [venmo/slather#68]
File this under question or feature request:

In their repo setup instructions, Coveralls warns against making your repo token public.  There are ways to do this for projects running PR builds on a public repo—though they aren't exactly bullet-proof.   It would be nice if slather supported passing the repo token using command-line args and/or environment variables. The fallback logic could look like:

- Env var?
- YAML?
- CL arg?
- Fail, no repo token provided

Thoughts?

**Comment by orta** [comment]
I've got a PR that adds an ENV var ^
