### ISSUE TITLE
Export to HTML

### ISSUE THREAD

**Issue by Ashton-W** [venmo/slather#82]
Should *slather* have HTML export?

`gcovr` can produce an ugly static html report, would be great if we could generate a pretty modern html report with some javascript to support filtering, reorder, etc within the page. Only restriction would be it needs to be able to run as a `file:///` url (no cross-origin)

**Comment by tarbrain** [comment]
I think something like this is already in the making.

see: https://github.com/venmo/slather/pull/76

**Comment by marklarr** [comment]
#76 is merged
