### ISSUE TITLE
Remove xcodeproj dependency?

### ISSUE THREAD

**Issue by soffes** [venmo/slather#86]
As far as I can tell, it's only used to add those two build options. It kills me to see it take forever to gem install xcodeproj, activesupport, etc on CI.

Maybe, `slather-core` that's just what you need on CI and keep xcodeproj in regular `slather`. Just a thought.

**Comment by kylef** [comment]
@soffes Most CI's support caches so you can probably eliminate the installing any dependencies.

- http://docs.travis-ci.com/user/caching/
- https://circleci.com/docs/how-cache-works

**Comment by soffes** [comment]
Good call @kylef
