### ISSUE TITLE
Wrong coverage on Coveralls

### ISSUE THREAD

**Issue by soffes** [venmo/slather#87]
[ISO8601](https://github.com/soffes/ISO8601) at [aeb5da75332954c9cd2f156edd8d8f83bbdef97e](https://github.com/soffes/ISO8601/commit/aeb5da75332954c9cd2f156edd8d8f83bbdef97e) shows 100% coverage locally (via `rake coverage`), but it only shows 86% [on Coveralls](https://coveralls.io/builds/2658105).

**Comment by soffes** [comment]
Re-ran a few times and still the old, wrong value: <https://coveralls.io/builds/2667766>

**Comment by erichoracek** [comment]
Having the same issue, this this might be due to a backlog in the coveralls processing queue: http://status.coveralls.io

**Comment by marklarr** [comment]
Is this resolved now?

**Comment by erichoracek** [comment]
@marklarr it is for me—Coveralls appears to have resolved their queue backlog issues. Regardless, this isn't a slather issue.

**Comment by marklarr** [comment]
@soffes I'll leave this for you to close out if you want

**Comment by soffes** [comment]
Fixed!
